### ISSUE TITLE
can your trained model be used to identify speaking with background music or lound noize?

### ISSUE THREAD

**Issue by superhg2012** [tomasz-oponowicz/spoken_language_identification#5]
Hi, I also working on LID, my online environment is not clean, there are bg musics or noize in online audio, how can I process this problem?

**Comment by tomasz-oponowicz** [comment]
Hi,

My proposal:

1. Open audio file
1. Until the end of the file
	1. Get next 1 second audio sample using sliding window
	1. The neural network recognizes (you have to develop this NN) if there is a human voice or not
	1. If yes then remember the start position
	1. If no and the start is defined then extract human voice
1. Squash all human voice samples into one audio file, for example `human-voice.flac`
1. Pass the `human-voice.flac` into SLI

The new neural network might be a simple CNN which accepts spectograms. As training data you can use:
- noise:
   - [Urban Sounds](https://serv.cusp.nyu.edu/projects/urbansounddataset/urbansound8k.html)
   - [Free Sound](http://freesound.org/)
   - [Free Music Archive](https://freemusicarchive.org)
- human voice:
   - [spoken_language_dataset](https://github.com/tomasz-oponowicz/spoken_language_dataset)


Last but not least you can try to improve SLI background noise tolerance by [increasing number of noisy samples in the dataset](https://github.com/tomasz-oponowicz/spoken_language_dataset/blob/master/generate.py#L36). Of course this is for samples which contain human voice and noise.

**Comment by tomasz-oponowicz** [comment]
One more thing... when you have samples divided into human voice and noise samples then you can use noise samples to create a noise profile. Next you can remove noise from human voice samples using newly created noise profile. I hope it will help!
