### ISSUE TITLE
Accuracy does not improve

### ISSUE THREAD

**Issue by nangongmu** [tomasz-oponowicz/spoken_language_identification#7]
Hi, accuracy does not improve when trainning the model(15G data). acc is just 0.34. Do you know why? Thank you.

**Comment by tomasz-oponowicz** [comment]
@nangongmu 

Sorry for the late reply. Crazy time here.

Can you provide more details?
Did you test on [the demo container](https://github.com/tomasz-oponowicz/spoken_language_identification#demo) (which contains the pre-generated model)?

Please mind that background noises may decrease accuracy significantly.
